# Getting Started with NumPy - Lab

## Introduction

Now that we have introduced NumPy, let's put it to practice. In this lab, we are going to be creating arrays, performing operations on them, and returning new array all using the NumPy library. Let's get started!

## Objectives

You will be able to: 

* Understand how to initialize NumPy arrays from nested Python lists, and access elements using square brackets
* Understand the shape attribute on NumPy arrays
* Understand how to create arrays from scratch including np.zeros, np.ones, np.full
* Learn to perform scalar and vector math  

## Import NumPy under the standard alias

In [1]:
#Your code here

## Generating Some Mock Data

Create a NumPy Array for each of the following:
    1. Using a range
    2. Using a Python List
    
Below, create a list in Python that has 5 elements (i.e. [0,1,2,3,4]) and assign it to the variable `py_list`. 

Next, do the same, but instead of a list, create a range with 5 elements and assign it to the variable, `py_range`.

Finally, use the list and range to create NumPy arrays and assign the array from list to the variable `array_from_list`, and the array from the range to the variable `array_from_range`.

In [1]:
#Your code here
py_list = [0,1,2,3,6]
py_range = range(5,10)
py_list_from_range = [x for x in py_range]
#print(py_list_from_range)

import numpy as np

array_from_list = np.array(py_list)
array_from_range = np.array([x for x in py_range])

In [4]:
array_from_range

array([5, 6, 7, 8, 9])

In [5]:
print(array_from_list)

[0 1 2 3 6]


Next, we have a list of heights and weights and we'd like to use them to create a collection of BMIs. However, they are both in inches and pounds (imperial system), respectively. 

Let's use what we know to create NumPy arrays with the metric equivalent values, (height in meters & weight in kg).

> **Remember:** *NumPy can make these calculations a lot easier and with less code than a list!*

> 1.0 inch = 0.0254 meters

> 2.2046 lbs = 1 kilogram

In [15]:
# use the conversion rate for turning height in inches to meters
list_height_inches = [65, 68, 73, 75, 78]
conversion_to_meters = np.array([.0254])
list_height_array_inches = np.array([list_height_inches])
list_height_m = np.array(list_height_array_inches*conversion_to_meters)
#Your code here

In [6]:
np.around(converted_array,2)



array([[1.65, 1.73, 1.85, 1.9 , 1.98]])

In [14]:
# use the conversion rate for turning weight in pounds to kilograms
list_weight_pounds = [150, 140, 220, 205, 265]
list_weight_kilos = np.array(list_weight_pounds)/np.array([2.20462])
print(np.around(np.array(list_weight_pounds)/np.array([2.20462]),2),' kilos')
#your code here

[ 68.04  63.5   99.79  92.99 120.2 ]  kilos


The metric formula for calculating BMI is as follows:

> BMI = weight (kg) ÷ height^2 (m^2)

So, to get BMI we divide weight by the squared value of height. For example, if i weighed 130kg and was 1.9 meters tall, the calculation would look like:

> BMI = 130 / (1.9*1.9)

Use the BMI calculation to create a NumPy array of BMIs

In [20]:
BMI = np.array( list_weight_kilos   / (list_height_m)**2)

In [24]:
print('BMI List: ',np.around(BMI,2))


BMI List:  [[24.96 21.29 29.03 25.62 30.62]]


## Create an identity vector using `np.ones()`

In [29]:
identity_vector = np.ones(5)

#Your code here

## Multiply the BMI_array by your identity vector

In [30]:
BMI*identity_vector

#Your code here

array([[24.96107985, 21.28673404, 29.02523766, 25.62301071, 30.62354704]])

## Level Up: Using NumPy to Parse a File
The pandas library that we've been using is built on top of NumPy; all columns/series in a Pandas DataFrame are built using NumPy arrays. To get a better idea of a how a built in method like pd.read_csv() works, we'll try and recreate that here!

In [37]:
f = open('bp.txt')
print(f.readlines())

['Pt\tBP\tAge\tWeight\tBSA\tDur\tPulse\tStress\n', '1\t105\t47\t85.4\t1.75\t5.1\t63\t33\n', '2\t115\t49\t94.2\t2.10\t3.8\t70\t14\n', '3\t116\t49\t95.3\t1.98\t8.2\t72\t10\n', '4\t117\t50\t94.7\t2.01\t5.8\t73\t99\n', '5\t112\t51\t89.4\t1.89\t7.0\t72\t95\n', '6\t121\t48\t99.5\t2.25\t9.3\t71\t10\n', '7\t121\t49\t99.8\t2.25\t2.5\t69\t42\n', '8\t110\t47\t90.9\t1.90\t6.2\t66\t8\n', '9\t110\t49\t89.2\t1.83\t7.1\t69\t62\n', '10\t114\t48\t92.7\t2.07\t5.6\t64\t35\n', '11\t114\t47\t94.4\t2.07\t5.3\t74\t90\n', '12\t115\t49\t94.1\t1.98\t5.6\t71\t21\n', '13\t114\t50\t91.6\t2.05\t10.2\t68\t47\n', '14\t106\t45\t87.1\t1.92\t5.6\t67\t80\n', '15\t125\t52\t101.3\t2.19\t10.0\t76\t98\n', '16\t114\t46\t94.5\t1.98\t7.4\t69\t95\n', '17\t106\t46\t87.0\t1.87\t3.6\t62\t18\n', '18\t113\t46\t94.5\t1.90\t4.3\t70\t12\n', '19\t110\t48\t90.5\t1.88\t9.0\t71\t99\n', '20\t122\t56\t95.7\t2.09\t7.0\t75\t99\n']


In [22]:
!head -n 100 bp.txt

Pt	BP	Age	Weight	BSA	Dur	Pulse	Stress
1	105	47	85.4	1.75	5.1	63	33
2	115	49	94.2	2.10	3.8	70	14
3	116	49	95.3	1.98	8.2	72	10
4	117	50	94.7	2.01	5.8	73	99
5	112	51	89.4	1.89	7.0	72	95
6	121	48	99.5	2.25	9.3	71	10
7	121	49	99.8	2.25	2.5	69	42
8	110	47	90.9	1.90	6.2	66	8
9	110	49	89.2	1.83	7.1	69	62
10	114	48	92.7	2.07	5.6	64	35
11	114	47	94.4	2.07	5.3	74	90
12	115	49	94.1	1.98	5.6	71	21
13	114	50	91.6	2.05	10.2	68	47
14	106	45	87.1	1.92	5.6	67	80
15	125	52	101.3	2.19	10.0	76	98
16	114	46	94.5	1.98	7.4	69	95
17	106	46	87.0	1.87	3.6	62	18
18	113	46	94.5	1.90	4.3	70	12
19	110	48	90.5	1.88	9.0	71	99
20	122	56	95.7	2.09	7.0	75	99


In [2]:
import numpy as np

In [10]:
#Open a text file (csv files are just plaintext separated by commas)
f = open('bp.txt')
n_rows = len(f.readlines())
#print('The file has {} lines.'.format(n_rows)) #Print number of lines in the file
f = open('bp.txt') #After using readlines, we must reopen the file
n_cols = (len(f.readline().split('\t'))) #The file has values separated by tabs; we read the first line and check it's length.

#line.split
#list of strings -- map to floats
#list of floats
#cast it into a numpy array
#assign to bp_array[i]

f = open('bp.txt')

bp_array = np.zeros((n_rows,n_cols,))
list_of_floats = []

for i, line in enumerate(f):
    list_of_strings=f.readline().split('\t')
    list_of_strings[-1] = list_of_strings[-1][:-2]
    
    
    string_ok = False
    for i in list_of_strings:
        if i != ' ':
            string_ok = True

    
    if string_ok
        list_of_floats = [float(x) for x in list_of_strings]
        bp_array[i] = list_of_floats


#print(n_cols)

# for x in range(1,n_rows):
#     for y in range(0,n_cols):
#         bp_array[x,y] = 


        
#bp_array

        
#bp_matrix[1,1]='f.readline()[0]'
# bp_array

#Your code here
#Pseudocode outline below
#1) Create a matrix of zeros that is the same size of the file
#2) Iterate through the file: "for line in f:" Hint: using enumerate will also be required
    #3) Update each row of the matrix with the new stream of data
    #Hint: skip the first row (it's just column names, not the data.)
#4) Preview your results; you should now have a NumPy matrix with the data from the file


SyntaxError: invalid syntax (<ipython-input-10-3358ee399f83>, line 26)

## Summary

In this lab, we practiced creating NumPy arrays from both lists and ranges. We then practiced performing math operations like converting imperial measurements to metric measurements on each element of a NumPy array to create new arrays with new values. Finally, we used both of our new NumPy arrays to operate on each other and create new arrays containing the BMIs from our arrays containing heights and weights.